github:
  description: "Website sources for the Travel Assistance Committee"
  homepage: https://tac.apache.org
  labels:
    - asf
    - travel
    - tac
    - hugo

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@tac.apache.org
  issues: commits@tac.apache.org
  pullrequests: commits@tac.apache.org
