baseURL = "https://tac.apache.org"
title = "ASF TAC"
languageCode = "en"

contentDir = "source"
publishDir = "target/content"

disablePathToLower = true
# uglyURLs = true # disable ugly
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ ] # No files to ignore

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[blackfriday]
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
# Source Code repository section
repositoryUrl = "https://github.com/apache/tac-website"
repositorySourceBranch = "main"

# Open Graph section
title = "Travel Assistance Committee (TAC)"
description = "The Travel Assistance Committee helps people get to ASF related events that they could not otherwise afford to attend."
# images = [] # Images are placed in `static/images`
tags = ["TAC", "Travel Assistance", "Apache Software Foundation"]
